### ISSUE TITLE
Creating a Block

### ISSUE THREAD

**Issue by atannerd** [mmwebaze/constant_contact_block#1]
First of all, thanks for your work on this module.  It installed and imported lists for me without a hitch.

However, it is not clear to me how to make a block that pushes an email to a list in the registered constant contact account.

What am I missing?

**Comment by mmwebaze** [comment]
Thanks for appreciating! Go to structure -> Block Layout and select the region you want to place the block in by clicking the 'Place block' button. In the filter search for constant contact and select 'Place block' button. Let me know if this works so I can close this issue.

**Comment by atannerd** [comment]
Totally worked.  I guess this was a pretty dumb question.  I was looking for the block without clicking "place block" first.  Thanks again!
